on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
jobs:
 run-tests:
   runs-on: ubuntu-latest
   steps:
   # Step 1: Check out the code from the repository
   - name: Check out repository
     uses: actions/checkout@v2
   # Step 2: Set up Java (for Java Selenium projects)
   - name: Set up JDK 11
     uses: actions/setup-java@v2
     with:
       java-version: '11'
   # Step 3: Install dependencies using Maven (if you are using Maven)
   - name: Install dependencies
     run: mvn install
   # Step 4: Run the tests
   - name: Run Selenium Tests
     run: mvn test
